name: Post Recession Indicator every 4 hours

on: 
  schedule: 
    - cron: '0 */4 * * *'

jobs: 
  post_skeet:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo 
        uses: actions/checkout@v4

      - name: nodejs setup 
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: dependencies install
        run: npm install

      - name: run indicator bot
        env: 
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: node bot_main.js